# Generated by Django 4.2 on 2023-05-01 02:51

from django.db import migrations
from django.core.management import call_command


def load_func(apps, schema_editor):
    call_command('loaddata', 'fixture_data.json')


def to_unload_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0001_initial"),
        ("sessions", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_func, to_unload_func)]
